/*
 * Copyright (C) 2010-2012 Strawberry-Pr0jcts <http://strawberry-pr0jcts.com/>
 * Copyright (C) 2005-2011 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"
#include "WorldSession.h"

enum Opcodes
{
    CMSG_ACCEPT_TRADE,
    CMSG_ADD_FRIEND,
    CMSG_ADD_IGNORE,
    CMSG_ARENA_TEAM_CACHE,
    CMSG_ATTACKSTOP,
    CMSG_ATTACKSWING,
    CMSG_AUTH_SESSION,
    CMSG_AUTOEQUIP_ITEM,
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESP,
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESP,
    CMSG_BATTLEFIELD_MGR_QUEUE_REQ,
    CMSG_BEGIN_TRADE,
    CMSG_BUSY_TRADE,
    CMSG_BUY_TRAINER_SERVICE,
    CMSG_CANCEL_AURA,
    CMSG_CANCEL_CAST,
    CMSG_CANCEL_TRADE,
    CMSG_CAST_SPELL,
    CMSG_CHAT_ADDON_MESSAGE_BATTLEGROUND,
    CMSG_CHAT_ADDON_MESSAGE_GUILD,
    CMSG_CHAT_ADDON_MESSAGE_OFFICER,
    CMSG_CHAT_ADDON_MESSAGE_PARTY,
    CMSG_CHAT_ADDON_MESSAGE_RAID,
    CMSG_CHAT_ADDON_MESSAGE_WHISPER,
    CMSG_CHAT_MESSAGE_AFK,
    CMSG_CHAT_MESSAGE_BATTLEGROUND,
    CMSG_CHAT_MESSAGE_CHANNEL,
    CMSG_CHAT_MESSAGE_DND,
    CMSG_CHAT_MESSAGE_EMOTE,
    CMSG_CHAT_MESSAGE_GUILD,
    CMSG_CHAT_MESSAGE_OFFICER,
    CMSG_CHAT_MESSAGE_PARTY,
    CMSG_CHAT_MESSAGE_RAID,
    CMSG_CHAT_MESSAGE_RAID_WARNING,
    CMSG_CHAT_MESSAGE_SAY,
    CMSG_CHAT_MESSAGE_WHISPER,
    CMSG_CHAT_MESSAGE_YELL,
    CMSG_CLEAR_TRADE_ITEM,
    CMSG_CONTACT_LIST,
    CMSG_CREATURE_STATS,
    CMSG_DANCE_CACHE,
    CMSG_DEL_FRIEND,
    CMSG_DEL_IGNORE,
    CMSG_DF_GET_SYSTEM_INFO,
    CMSG_EMOTE,
    CMSG_FORCE_MOVE_ROOT_ACK,
    CMSG_FORCE_MOVE_UNROOT_ACK,
    CMSG_GAME_OBJECT_STATS,
    CMSG_GET_CALENDER,
    CMSG_GOSSIP_HELLO,
    CMSG_GOSSIP_SELECT_OPTION,
    CMSG_GROUP_INVITE,
    CMSG_GROUP_SET_LEADER,
    CMSG_GUILD_ADD_RANK,
    CMSG_GUILD_BANK_BUY_TAB,
    CMSG_GUILD_CACHE,
    CMSG_GUILD_DEL_RANK,
    CMSG_GUILD_INFO,
    CMSG_GUILD_INFO_TEXT,
    CMSG_GUILD_LEAVE,
    CMSG_GUILD_MOTD,
    CMSG_GUILD_ORDER_RANK,
    CMSG_GUILD_RANK,
    CMSG_GUILD_RANKS,
    CMSG_GUILD_REWARDS_LIST,
    CMSG_GUILD_ROSTER,
    CMSG_IGNORE_TRADE,
    CMSG_INITIATE_TRADE,
    CMSG_ITEM_TEXT_CACHE,
    CMSG_JOIN_CHANNEL,
    CMSG_LEARN_PREVIEW_TALENTS,
    CMSG_LEARN_TALENT,
    CMSG_LIST_INVENTORY,
    CMSG_LOADING_SCREEN_NOTIFY,
    CMSG_LOGOUT_CANCEL,
    CMSG_LOGOUT_REQUEST,
    CMSG_LOG_DISCONNECT,
    CMSG_MOVE_TIME_SKIPPED,
    CMSG_NAME_CACHE,
    CMSG_NPC_CACHE,
    CMSG_OPENING_CINEMATIC,
    CMSG_PAGE_TEXT_CACHE,
    CMSG_PETITION_CACHE,
    CMSG_PET_NAME_CACHE,
    CMSG_PING,
    CMSG_PLAYED_TIME,
    CMSG_PLAYER_LOGIN,
    CMSG_PLAYER_LOGOUT,
    CMSG_QUERY_INSPECT_ACHIEVEMENTS,
    CMSG_QUERY_TIME,
    CMSG_QUESTGIVER_ACCEPT_QUEST,
    CMSG_QUESTGIVER_CHOOSE_REWARD,
    CMSG_QUESTGIVER_COMPLETE_QUEST,
    CMSG_QUESTGIVER_HELLO,
    CMSG_QUESTGIVER_QUERY_QUEST,
    CMSG_QUESTGIVER_REQUEST_REWARD,
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY,
    CMSG_QUESTGIVER_STATUS_QUERY,
    CMSG_QUESTLOG_REMOVE_QUEST,
    CMSG_QUEST_CONFIRM_ACCEPT,
    CMSG_QUEST_POI_QUERY,
    CMSG_QUEST_QUERY,
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES,
    CMSG_REALM_SPLIT_STATE,
    CMSG_REQUEST_ACCOUNT_DATA,
    CMSG_REQUEST_BATTLEFIELD_STATUS,
    CMSG_REQUEST_CATEGORY_COOLDOWNS,
    CMSG_REQUEST_CHARACTER_CREATE,
    CMSG_REQUEST_CHARACTER_DELETE,
    CMSG_REQUEST_CHARACTER_ENUM,
    CMSG_REQUEST_RAID_INFO,
    CMSG_SET_ACTIONBAR_TOGGLES,
    CMSG_SET_ACTION_BUTTON,
    CMSG_SET_CONTACT_NOTES,
    CMSG_SET_SELECTION,
    CMSG_SET_TRADE_GOLD,
    CMSG_SET_TRADE_ITEM,
    CMSG_SPIRIT_HEALER_ACTIVATE,
    CMSG_STANDSTATECHANGE,
    CMSG_SWAP_INV_ITEM,
    CMSG_SWAP_ITEM,
    CMSG_TEXT_EMOTE,
    CMSG_TIME_SYNC_RESPONSE,
    CMSG_TRAINER_LIST,
    CMSG_TUTORIAL_FLAG,
    CMSG_UI_TIME_REQUEST,
    CMSG_UNACCEPT_TRADE,
    CMSG_UPDATE_ACCOUNT_DATA,
    CMSG_UPDATE_OBJECT_FAILURE,
    CMSG_UPDATE_PROGRESS_BAR,
    CMSG_VALIDATE_TIMER,
    CMSG_VIOLENCE_LEVEL,
    CMSG_VOICE_SESSION_ENABLE,
    CMSG_WHO,
    CMSG_WHOIS,
    CMSG_WORLD_TELEPORT,
    CMSG_ZONEUPDATE,
    MSG_MOVE_FALL_LAND,
    MSG_MOVE_HEARTBEAT,
    MSG_MOVE_JUMP,
    MSG_MOVE_SET_FACING,
    MSG_MOVE_SET_PITCH,
    MSG_MOVE_START_ASCEND,
    MSG_MOVE_START_BACKWARD,
    MSG_MOVE_START_DESCEND,
    MSG_MOVE_START_FORWARD,
    MSG_MOVE_START_PITCH_DOWN,
    MSG_MOVE_START_PITCH_UP,
    MSG_MOVE_START_STRAFE_LEFT,
    MSG_MOVE_START_STRAFE_RIGHT,
    MSG_MOVE_START_SWIM,
    MSG_MOVE_START_TURN_LEFT,
    MSG_MOVE_START_TURN_RIGHT,
    MSG_MOVE_STOP,
    MSG_MOVE_STOP_ASCEND,
    MSG_MOVE_STOP_PITCH,
    MSG_MOVE_STOP_STRAFE,
    MSG_MOVE_STOP_SWIM,
    MSG_MOVE_STOP_TURN,
    MSG_MOVE_TELEPORT,
    MSG_MOVE_TELEPORT_ACK,
    MSG_MOVE_WORLDPORT_ACK,
    MSG_QUERY_NEXT_MAIL_TIME,
    MSG_SET_DUNGEON_DIFFICULTY,
    MSG_TALENT_WIPE_CONFIRM,
    MSG_WOW_CONNECTION,
    SMSG_ACCOUNT_DATA_INITIALIZED,
    SMSG_ACHIEVEMENT_DELETED,
    SMSG_ACHIEVEMENT_EARNED,
    SMSG_ACHIEVEMENT_RESPONSE,
    SMSG_ACTION_BUTTONS,
    SMSG_ADDON_INFO,
    SMSG_ALL_ACHIEVEMENT_DATA,
    SMSG_ALL_GUILD_ACHIEVEMENTS,
    SMSG_ALL_QUEST_DATA,
    SMSG_ARENA_TEAM_CACHE,
    SMSG_ARENA_TEAM_ROSTER,
    SMSG_ARENA_TEAM_STATS,
    SMSG_ATTACKERSTATEUPDATE,
    SMSG_ATTACKSTART,
    SMSG_ATTACKSTOP,
    SMSG_ATTACKSWING_BADFACING,
    SMSG_ATTACKSWING_CANT_ATTACK,
    SMSG_ATTACKSWING_DEADTARGET,
    SMSG_ATTACKSWING_NOTINRANGE,
    SMSG_AUCTION_COMMAND_RESULT,
    SMSG_AUCTION_HELLO,
    SMSG_AUCTION_LIST,
    SMSG_AUCTION_REMOVED_NOTIFICATION,
    SMSG_AURA_UPDATE,
    SMSG_AURA_UPDATE_ALL,
    SMSG_AUTH_CHALLENGE,
    SMSG_AUTH_RESPONSE,
    SMSG_BARBER_SHOP_RESULT,
    SMSG_BATTLEFIELD_LIST,
    SMSG_BATTLEFIELD_MGR_ENTERING,
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE,
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE,
    SMSG_BATTLEFIELD_MGR_QUEUE_REQ_RESP,
    SMSG_BATTLEFIELD_MGR_STATE_CHANGED,
    SMSG_BATTLEFIELD_PLAYER_JOINED,
    SMSG_BATTLEFIELD_PLAYER_LEFT,
    SMSG_BATTLEFIELD_PLAYER_POSITIONS,
    SMSG_BATTLEFIELD_PORT_DENIED,
    SMSG_BATTLEFIELD_STATUS_ACTIVE,
    SMSG_BATTLEFIELD_STATUS_FAILED,
    SMSG_BATTLEFIELD_STATUS_NEED_CONFIRMATION,
    SMSG_BATTLEFIELD_STATUS_NONE,
    SMSG_BATTLEFIELD_STATUS_QUEUED,
    SMSG_BATTLEFIELD_STATUS_WAIT_FOR_GROUPS,
    SMSG_BF_MGR_EJECTED,
    SMSG_BF_MGR_EJECT_PENDING,
    SMSG_BF_MGR_ENTERING,
    SMSG_BIDDER_AUCTION_LIST,
    SMSG_BIDDER_NOTIFICATION,
    SMSG_CAST_FAILED,
    SMSG_CHANGE_PLAYER_DIFFICULTY_RESULT,
    SMSG_CHANNEL_LIST,
    SMSG_CHANNEL_MEMBER_COUNT,
    SMSG_CHANNEL_NOTIFY,
    SMSG_CHAR_DELETE,
    SMSG_CHAT_DOWN,
    SMSG_CHAT_IS_DOWN,
    SMSG_CHAT_RECONNECT,
    SMSG_CHECK_RELOAD_SPAM_FILTER,
    SMSG_CHECK_WARGAME_ENTRY,
    SMSG_CLEAR_COOLDOWNS,
    SMSG_CLEAR_TARGET,
    SMSG_CLIENTCACHE_VERSION,
    SMSG_COMBAT_EVENT_FAILED,
    SMSG_COMMENTATOR_PARTY_INFO,
    SMSG_COMPRESSED_UPDATE_OBJECT,
    SMSG_COMSAT_CONNECT_DISCONNECT,
    SMSG_COMSAT_CONNECT_FAIL,
    SMSG_COMSAT_RECONNECT_ATTEMPT,
    SMSG_CONTACT_LIST,
    SMSG_CORPSE_RECLAIM_DELAY,
    SMSG_CREATURE_STATS,
    SMSG_CRITERIA_DELETED,
    SMSG_CRITERIA_UPDATE,
    SMSG_CURRENCY_LOOT_REMOVED,
    SMSG_CURRENCY_LOOT_RESTORED,
    SMSG_DANCE_CACHE,
    SMSG_DB_REPLY,
    SMSG_DEFENSE_MESSAGE,
    SMSG_DESTROY_ARENA_UNIT,
    SMSG_DESTROY_OBJECT,
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE,
    SMSG_DISPEL_FAILED,
    SMSG_DUEL_COMPLETE,
    SMSG_DUEL_COUNTDOWN,
    SMSG_DUEL_IN_BOUNDS,
    SMSG_DUEL_OUT_OF_BOUNDS,
    SMSG_DUEL_REQUESTED,
    SMSG_DUEL_WINNER,
    SMSG_DURABILITY_DAMAGE_DEATH,
    SMSG_ECHO_SQUELCH,
    SMSG_EMOTE,
    SMSG_ENABLE_BARBER_SHOP,
    SMSG_ENCHANTMENTLOG,
    SMSG_ENVIRONMENTALDAMAGELOG,
    SMSG_EQUIPMENT_SET,
    SMSG_EQUIPMENT_SET_ID,
    SMSG_EQUIPMENT_SET_RESULT,
    SMSG_EVENT_LIST,
    SMSG_EVENT_REMOVED_ALERT,
    SMSG_EVENT_UPDATED_ALERT,
    SMSG_FEATURE_SYSTEM_STATUS,
    SMSG_FLIGHT_SPLINE_SYNC,
    SMSG_FORCE_MOVE_ROOT,
    SMSG_FORCE_MOVE_UNROOT,
    SMSG_FRIEND_STATUS,
    SMSG_GAMESPEED_SET,
    SMSG_GAMETIME_SET,
    SMSG_GAMETIME_UPDATE,
    SMSG_GAME_OBJECT_STATS,
    SMSG_GET_EVENT,
    SMSG_GET_LEARNED_DANCE_MOVES,
    SMSG_GM_MESSAGE_CHAT,
    SMSG_GOSSIP_COMPLETE,
    SMSG_GOSSIP_MESSAGE,
    SMSG_GOSSIP_POI,
    SMSG_GROUP_LIST,
    SMSG_GROUP_SET_LEADER,
    SMSG_GUILD_ACHIEVEMENT_DELETED,
    SMSG_GUILD_ACHIEVEMENT_EARNED,
    SMSG_GUILD_ACHIEVEMENT_MEMBERS,
    SMSG_GUILD_BANK_LIST,
    SMSG_GUILD_BANK_LOG,
    SMSG_GUILD_BANK_MONEY_WITHDRAWN,
    SMSG_GUILD_BANK_TEXT,
    SMSG_GUILD_CACHE,
    SMSG_GUILD_COMMAND_RESULT,
    SMSG_GUILD_CRITERIA_DELETED,
    SMSG_GUILD_CRITERIA_UPDATE,
    SMSG_GUILD_EVENT,
    SMSG_GUILD_INFO,
    SMSG_GUILD_RANKS,
    SMSG_GUILD_REWARDS_LIST,
    SMSG_GUILD_ROSTER,
    SMSG_INITIALIZE_FACTIONS,
    SMSG_INITIAL_INVITE_LIST,
    SMSG_INITIAL_SPELLS,
    SMSG_INIT_WORLD_STATES,
    SMSG_INSPECT_ARENA_TEAMS,
    SMSG_INSPECT_HONOR_STATS,
    SMSG_INSPECT_RATED_BG_STATS,
    SMSG_INSTANCE_DIFFICULTY,
    SMSG_INSTANCE_RESET,
    SMSG_INSTANCE_RESET_FAILED,
    SMSG_INSTANCE_SAVE_RESULT,
    SMSG_INVITE,
    SMSG_INVITE_ALERT,
    SMSG_INVITE_MODERATOR_STATUS_ALERT,
    SMSG_INVITE_NOTES,
    SMSG_INVITE_NOTES_ALERT,
    SMSG_INVITE_REMOVED,
    SMSG_INVITE_REMOVED_ALERT,
    SMSG_INVITE_STATUS,
    SMSG_INVITE_STATUS_ALERT,
    SMSG_ITEM_TEXT_CACHE,
    SMSG_LEARNED_SPELL,
    SMSG_LEVELUP_INFO,
    SMSG_LFG_DISABLED,
    SMSG_LFG_JOIN_RESULT,
    SMSG_LFG_LIST,
    SMSG_LFG_OFFER_CONTINUE,
    SMSG_LFG_PARTY_INFO,
    SMSG_LFG_PLAYER_REWARD,
    SMSG_LFG_PROPOSAL_UPDATE,
    SMSG_LFG_QUEUE_STATUS,
    SMSG_LFG_ROLE_CHECK_UPDATE,
    SMSG_LFG_TELEPORT_DENIED,
    SMSG_LFG_UPDATE_PARTY,
    SMSG_LFG_UPDATE_PLAYER,
    SMSG_LFG_UPDATE_SEARCH,
    SMSG_LF_GUILD_APPLICANT_LIST_CHANGED,
    SMSG_LF_GUILD_APPLICATIONS,
    SMSG_LF_GUILD_APPLICATIONS_LIST_CHANGED,
    SMSG_LF_GUILD_BROWSE,
    SMSG_LF_GUILD_COMMAND_RESULT,
    SMSG_LF_GUILD_POST,
    SMSG_LF_GUILD_RECRUITS,
    SMSG_LIST_INVENTORY,
    SMSG_LOCKOUT_ADDED,
    SMSG_LOCKOUT_REMOVED,
    SMSG_LOCKOUT_UPDATED,
    SMSG_LOGIN_SETTIMESPEED,
    SMSG_LOGIN_VERIFY_WORLD,
    SMSG_LOGOUT_CANCEL,
    SMSG_LOGOUT_COMPLETE,
    SMSG_LOGOUT_RESPONSE,
    SMSG_LOG_XPGAIN,
    SMSG_MAIL_COMMAND_RESULT,
    SMSG_MAIL_LIST_RESULT,
    SMSG_MESSAGE_CHAT,
    SMSG_MINIGAME_SETUP,
    SMSG_MINIGAME_STATE,
    SMSG_MONSTER_MOVE,
    SMSG_MOTD,
    SMSG_MOVE_SET_CAN_FLY,
    SMSG_MOVE_SET_FLIGHT_BACK_SPEED,
    SMSG_MOVE_SET_FLIGHT_SPEED,
    SMSG_MOVE_SET_PITCH_RATE,
    SMSG_MOVE_SET_RUN_BACK_SPEED,
    SMSG_MOVE_SET_RUN_SPEED,
    SMSG_MOVE_SET_SWIM_BACK_SPEED,
    SMSG_MOVE_SET_SWIM_SPEED,
    SMSG_MOVE_SET_TURN_RATE,
    SMSG_MOVE_SET_WALK_SPEED,
    SMSG_MOVE_UNSET_CAN_FLY,
    SMSG_MSG_LFG_PLAYER_INFO,
    SMSG_NAME_CACHE,
    SMSG_NEW_WORLD,
    SMSG_NOTIFY_DANCE,
    SMSG_NPC_CACHE,
    SMSG_OFFER_PETITION_ERROR,
    SMSG_OPEN_FROM_GOSSIP,
    SMSG_OWNER_AUCTION_LIST,
    SMSG_OWNER_NOTIFICATION,
    SMSG_OWNER_PENDING_SALES_LIST,
    SMSG_PAGE_TEXT_CACHE,
    SMSG_PARTYKILLLOG,
    SMSG_PARTY_COMMAND_RESULT,
    SMSG_PERIODICAURALOG,
    SMSG_PETITION_CACHE,
    SMSG_PET_ACTION_FEEDBACK,
    SMSG_PET_ADDED,
    SMSG_PET_BROKEN,
    SMSG_PET_GUIDS,
    SMSG_PET_MODE,
    SMSG_PET_NAME_CACHE,
    SMSG_PET_RENAMEABLE,
    SMSG_PET_SLOT_UPDATED,
    SMSG_PET_SPELLS,
    SMSG_PET_SPELL_CHANGES,
    SMSG_PET_SPELL_CHANGES1,
    SMSG_PET_UPDATE_COMBO_POINTS,
    SMSG_PHASE_SHIFT_CHANGE,
    SMSG_PLAYED_TIME,
    SMSG_PLAYER_MOVE,
    SMSG_PLAYER_SQUELCHED,
    SMSG_PLAY_DANCE,
    SMSG_PLAY_SOUND,
    SMSG_PLAY_SPELL_VISUAL,
    SMSG_PONG,
    SMSG_POSTMASTER_ACTIVATE,
    SMSG_POWER_UPDATE,
    SMSG_PROCRESIST,
    SMSG_PVP_LOG_DATA,
    SMSG_PVP_OPTIONS_ENABLED,
    SMSG_QUERY_TIME_RESPONSE,
    SMSG_QUESTGIVER_OFFER_REWARD,
    SMSG_QUESTGIVER_QUEST_COMPLETE,
    SMSG_QUESTGIVER_QUEST_DETAILS,
    SMSG_QUESTGIVER_QUEST_FAILED,
    SMSG_QUESTGIVER_QUEST_INVALID,
    SMSG_QUESTGIVER_QUEST_LIST,
    SMSG_QUESTGIVER_REQUEST_ITEMS,
    SMSG_QUESTGIVER_STATUS,
    SMSG_QUESTGIVER_STATUS_MULTIPLE,
    SMSG_QUESTLOG_FULL,
    SMSG_QUEST_CONFIRM_ACCEPT,
    SMSG_QUEST_QUERY_RESPONSE,
    SMSG_RAID_INSTANCE_INFO,
    SMSG_RAID_INSTANCE_MESSAGE,
    SMSG_RAID_TARGET_UPDATE,
    SMSG_RATED_BATTLEFIELD_INFO,
    SMSG_RATED_BG_STATS,
    SMSG_READY_CHECK,
    SMSG_READY_CHECK_CONFIRM,
    SMSG_READY_CHECK_ERROR,
    SMSG_READY_CHECK_FINISHED,
    SMSG_REALM_SPLIT_MSG,
    SMSG_RECEIVED_MAIL,
    SMSG_RECEIVE_MAP_INFO,
    SMSG_RECEIVE_PLAYER_INFO,
    SMSG_REMOVED_SPELL,
    SMSG_RESEARCH_COMPLETE,
    SMSG_RESET_FAILED_NOTIFY,
    SMSG_RESET_WEEKLY_CURRENCY,
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS,
    SMSG_RESPONSE_CHARACTER_CREATE,
    SMSG_RESPONSE_CHARACTER_ENUM,
    SMSG_ROLE_CHOSEN,
    SMSG_SAVE_BIND_POINT,
    SMSG_SEND_UNLEARN_SPELLS,
    SMSG_SERVERTIME,
    SMSG_SERVER_FIRST_ACHIEVEMENT,
    SMSG_SERVER_MESSAGE,
    SMSG_SETUP_CURRENCY,
    SMSG_SETUP_RESEARCH_HISTORY,
    SMSG_SET_CURRENCY,
    SMSG_SET_FACTION_AT_WAR,
    SMSG_SET_FACTION_VISIBLE,
    SMSG_SET_FACTION_VISIBLE1,
    SMSG_SET_FATION_STANDING,
    SMSG_SET_FLAT_SPELL_MODIFIER,
    SMSG_SET_FORCED_REACTIONS,
    SMSG_SET_MAX_WEEKLY_QUANTITY,
    SMSG_SET_PCT_SPELL_MODIFIER,
    SMSG_SET_PROFICIENCY,
    SMSG_SKIRMISH_PLAYERS_IN_QUEUE,
    SMSG_SKIRMISH_PLAYERS_MODE_STATE,
    SMSG_SPELLLOGEXECUTE,
    SMSG_SPELL_COOLDOWN,
    SMSG_SPELL_GO,
    SMSG_SPELL_START,
    SMSG_SPLINE_MOVE_SET_FLIGHT_BACK_SPEED,
    SMSG_SPLINE_MOVE_SET_FLIGHT_SPEED,
    SMSG_SPLINE_MOVE_SET_PITCH_RATE,
    SMSG_SPLINE_MOVE_SET_RUN_BACK_SPEED,
    SMSG_SPLINE_MOVE_SET_RUN_SPEED,
    SMSG_SPLINE_MOVE_SET_SWIM_BACK_SPEED,
    SMSG_SPLINE_MOVE_SET_SWIM_SPEED,
    SMSG_SPLINE_MOVE_SET_TURN_RATE,
    SMSG_SPLINE_MOVE_SET_WALK_SPEED,
    SMSG_STABLE_COMMAND_RESULT,
    SMSG_STABLE_LIST,
    SMSG_STANDSTATE_UPDATE,
    SMSG_START_CINEMATIC,
    SMSG_STATE_CHANGED,
    SMSG_STOP_DANCE,
    SMSG_STREAMING_MOVIES,
    SMSG_TALENT_UPDATE,
    SMSG_TEXT_EMOTE,
    SMSG_TIME_SYNC_REQ,
    SMSG_TITLE_EARNED,
    SMSG_TRADE_STATUS,
    SMSG_TRADE_STATUS_EXTENDED,
    SMSG_TRADE_UPDATED,
    SMSG_TRAINER_BUY_FAILED,
    SMSG_TRAINER_BUY_SUCCEEDED,
    SMSG_TRAINER_LIST,
    SMSG_TRANSFER_ABORTED,
    SMSG_TRANSFER_PENDING,
    SMSG_TUTORIAL_FLAGS,
    SMSG_UI_TIME,
    SMSG_UPDATE_ACCOUNT_DATA,
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE,
    SMSG_UPDATE_INSTANCE,
    SMSG_UPDATE_INSTANCE_OWNERSHIP,
    SMSG_UPDATE_OBJECT,
    SMSG_UPDATE_WORLD_STATE,
    SMSG_USER_LIST_ADDED,
    SMSG_USER_LIST_REMOVE,
    SMSG_USER_LIST_UPDATE,
    SMSG_VOICESESSION_FULL,
    SMSG_VOICE_STATUS_CHANGED,
    SMSG_WARDEN_DATA,
    SMSG_WARGAME_REQUEST_SUCCESSFULLY_SENT_TO_OPPONENT,
    SMSG_WHO,
    SMSG_WHOIS,
    SMSG_ZONE_UNDER_ATTACK,

    MAX_OPCODE_VALUE,

    // unupdated 3.3.5 upcodes
    CMSG_ACCEPT_LEVEL_GRANT,                     // = 0x420,
    CMSG_ACTIVATETAXI,                           // = 0x1AD,
    CMSG_ACTIVATETAXIEXPRESS,                    // = 0x312,
    CMSG_ACTIVE_PVP_CHEAT,                       // = 0x399,
    CMSG_ADD_PVP_MEDAL_CHEAT,                    // = 0x289,
    CMSG_ADD_VOICE_IGNORE,                       // = 0x3DB,
    CMSG_ADVANCE_SPAWN_TIME,                     // = 0x031,
    CMSG_AFK_MONITOR_INFO_CLEAR,                 // = 0x505,
    CMSG_AFK_MONITOR_INFO_REQUEST,               // = 0x503,
    CMSG_ALTER_APPEARANCE,                       // = 0x426,
    CMSG_AREATRIGGER,                            // = 0x0B4,
    CMSG_AREA_SPIRIT_HEALER_QUERY,               // = 0x2E2,
    CMSG_AREA_SPIRIT_HEALER_QUEUE,               // = 0x2E3,
    CMSG_ARENA_TEAM_ACCEPT,                      // = 0x351,
    CMSG_ARENA_TEAM_CREATE,                      // = 0x348,
    CMSG_ARENA_TEAM_DECLINE,                     // = 0x352,
    CMSG_ARENA_TEAM_DISBAND,                     // = 0x355,
    CMSG_ARENA_TEAM_INVITE,                      // = 0x34F,
    CMSG_ARENA_TEAM_LEADER,                      // = 0x356,
    CMSG_ARENA_TEAM_LEAVE,                       // = 0x353,
    CMSG_ARENA_TEAM_REMOVE,                      // = 0x354,
    CMSG_ARENA_TEAM_ROSTER,                      // = 0x34D,
    CMSG_AUCTION_LIST_BIDDER_ITEMS,              // = 0x264,
    CMSG_AUCTION_LIST_ITEMS,                     // = 0x258,
    CMSG_AUCTION_LIST_OWNER_ITEMS,               // = 0x259,
    CMSG_AUCTION_LIST_PENDING_SALES,             // = 0x48F,
    CMSG_AUCTION_PLACE_BID,                      // = 0x25A,
    CMSG_AUCTION_REMOVE_ITEM,                    // = 0x257,
    CMSG_AUCTION_SELL_ITEM,                      // = 0x256,
    CMSG_AUTH_CONTINUED_SESSION,                 // = 0x512,
    CMSG_AUTH_SRP6_BEGIN,                        // = 0x033,
    CMSG_AUTH_SRP6_PROOF,                        // = 0x034,
    CMSG_AUTH_SRP6_RECODE,                       // = 0x035,
    CMSG_AUTOBANK_ITEM,                          // = 0x283,
    CMSG_AUTOEQUIP_GROUND_ITEM,                  // = 0x106,
    CMSG_AUTOEQUIP_ITEM_SLOT,                    // = 0x10F,
    CMSG_AUTOSTORE_BAG_ITEM,                     // = 0x10B,
    CMSG_AUTOSTORE_BANK_ITEM,                    // = 0x282,
    CMSG_AUTOSTORE_GROUND_ITEM,                  // = 0x107,
    CMSG_AUTOSTORE_LOOT_ITEM,                    // = 0x108,
    CMSG_BANKER_ACTIVATE,                        // = 0x1B7,
    CMSG_BATTLEFIELD_JOIN,                       // = 0x23E,
    CMSG_BATTLEFIELD_LIST,                       // = 0x23C,
    CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE,      // = 0x4E9,
    CMSG_BATTLEFIELD_MANAGER_EXIT_REQUEST,       // = 0x4E7,
    CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANSITION_TIME, // = 0x4EA,
    CMSG_BATTLEFIELD_PORT,                       // = 0x2D5,
    CMSG_BATTLEMASTER_HELLO,                     // = 0x2D7,
    CMSG_BATTLEMASTER_JOIN,                      // = 0x2EE,
    CMSG_BATTLEMASTER_JOIN_ARENA,                // = 0x358,
    CMSG_BEASTMASTER,                            // = 0x021,
    CMSG_BINDER_ACTIVATE,                        // = 0x1B5,
    CMSG_BOOTME,                                 // = 0x001,
    CMSG_BOT_DETECTED,                           // = 0x3C0,
    CMSG_BOT_DETECTED2,                          // = 0x017,
    CMSG_BUG,                                    // = 0x1CA,
    CMSG_BUYBACK_ITEM,                           // = 0x290,
    CMSG_BUY_BANK_SLOT,                          // = 0x1B9,
    CMSG_BUY_ITEM,                               // = 0x1A2,
    CMSG_BUY_ITEM_IN_SLOT,                       // = 0x1A3,
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE,            // = 0x336,
    CMSG_BUY_STABLE_SLOT,                        // = 0x272,
    CMSG_CALENDAR_ADD_EVENT,                     // = 0x42D,
    CMSG_CALENDAR_ARENA_TEAM,                    // = 0x42C,
    CMSG_CALENDAR_COMPLAIN,                      // = 0x446,
    CMSG_CALENDAR_COPY_EVENT,                    // = 0x430,
    CMSG_CALENDAR_EVENT_INVITE,                  // = 0x431,
    CMSG_CALENDAR_EVENT_INVITE_NOTES,            // = 0x45F,
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS,        // = 0x435,
    CMSG_CALENDAR_EVENT_REMOVE_INVITE,           // = 0x433,
    CMSG_CALENDAR_EVENT_RSVP,                    // = 0x432,
    CMSG_CALENDAR_EVENT_SIGNUP,                  // = 0x4BA,
    CMSG_CALENDAR_EVENT_STATUS,                  // = 0x434,
    CMSG_CALENDAR_GET_EVENT,                     // = 0x42A,
    CMSG_CALENDAR_GET_NUM_PENDING,               // = 0x447,
    CMSG_CALENDAR_GUILD_FILTER,                  // = 0x42B,
    CMSG_CALENDAR_REMOVE_EVENT,                  // = 0x42F,
    CMSG_CALENDAR_UPDATE_EVENT,                  // = 0x42E,
    CMSG_CANCEL_AUTO_REPEAT_SPELL,               // = 0x26D,
    CMSG_CANCEL_CHANNELLING,                     // = 0x13B,
    CMSG_CANCEL_GROWTH_AURA,                     // = 0x29B,
    CMSG_CANCEL_MOUNT_AURA,                      // = 0x375,
    CMSG_CANCEL_TEMP_ENCHANTMENT,                // = 0x379,
    CMSG_CHANGEPLAYER_DIFFICULTY,                // = 0x1FD,
    CMSG_CHANGE_GDF_ARENA_RATING,                // = 0x4AC,
    CMSG_CHANGE_PERSONAL_ARENA_RATING,           // = 0x425,
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE,     // = 0x49B,
    CMSG_CHANNEL_ANNOUNCEMENTS,                  // = 0x0A7,
    CMSG_CHANNEL_BAN,                            // = 0x0A5,
    CMSG_CHANNEL_DISPLAY_LIST,                   // = 0x3D2,
    CMSG_CHANNEL_INVITE,                         // = 0x0A3,
    CMSG_CHANNEL_KICK,                           // = 0x0A4,
    CMSG_CHANNEL_LIST,                           // = 0x09A,
    CMSG_CHANNEL_MODERATE,                       // = 0x0A8,
    CMSG_CHANNEL_MODERATOR,                      // = 0x09F,
    CMSG_CHANNEL_MUTE,                           // = 0x0A1,
    CMSG_CHANNEL_OWNER,                          // = 0x09E,
    CMSG_CHANNEL_PASSWORD,                       // = 0x09C,
    CMSG_CHANNEL_SET_OWNER,                      // = 0x09D,
    CMSG_CHANNEL_SILENCE_ALL,                    // = 0x3CD,
    CMSG_CHANNEL_SILENCE_VOICE,                  // = 0x3CC,
    CMSG_CHANNEL_UNBAN,                          // = 0x0A6,
    CMSG_CHANNEL_UNMODERATOR,                    // = 0x0A0,
    CMSG_CHANNEL_UNMUTE,                         // = 0x0A2,
    CMSG_CHANNEL_UNSILENCE_ALL,                  // = 0x3CF,
    CMSG_CHANNEL_UNSILENCE_VOICE,                // = 0x3CE,
    CMSG_CHANNEL_VOICE_OFF,                      // = 0x3D7,
    CMSG_CHANNEL_VOICE_ON,                       // = 0x3D6,
    CMSG_CHARACTER_POINT_CHEAT,                  // = 0x223,
    CMSG_CHAR_CUSTOMIZE,                         // = 0x473,
    CMSG_CHAR_DELETE,                            // = 0x038,
    CMSG_CHAR_FACTION_CHANGE,                    // = 0x4D9,
    CMSG_CHAR_RACE_CHANGE,                       // = 0x4F8,
    CMSG_CHAR_RENAME,                            // = 0x2C7,
    CMSG_CHAT_FILTERED,                          // = 0x331,
    CMSG_CHAT_IGNORED,                           // = 0x225,
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY,            // = 0x39A,
    CMSG_CHEAT_PLAYER_LOGIN,                     // = 0x3C2,
    CMSG_CHEAT_PLAYER_LOOKUP,                    // = 0x3C3,
    CMSG_CHEAT_SETMONEY,                         // = 0x024,
    CMSG_CHEAT_SET_ARENA_CURRENCY,               // = 0x37C,
    CMSG_CHEAT_SET_HONOR_CURRENCY,               // = 0x37B,
    CMSG_CHECK_LOGIN_CRITERIA,                   // = 0x4A2,
    CMSG_CLEAR_CHANNEL_WATCH,                    // = 0x3F3,
    CMSG_CLEAR_EXPLORATION,                      // = 0x237,
    CMSG_CLEAR_HOLIDAY_BG_WIN_TIME,              // = 0x51A,
    CMSG_CLEAR_QUEST,                            // = 0x02C,
    CMSG_CLEAR_RANDOM_BG_WIN_TIME,               // = 0x519,
    CMSG_CLEAR_SERVER_BUCK_DATA,                 // = 0x41C,
    CMSG_COMMENTATOR_ENABLE,                     // = 0x3B5,
    CMSG_COMMENTATOR_ENTER_INSTANCE,             // = 0x3BC,
    CMSG_COMMENTATOR_EXIT_INSTANCE,              // = 0x3BD,
    CMSG_COMMENTATOR_GET_MAP_INFO,               // = 0x3B7,
    CMSG_COMMENTATOR_GET_PLAYER_INFO,            // = 0x3B9,
    CMSG_COMMENTATOR_INSTANCE_COMMAND,           // = 0x3BE,
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND,     // = 0x51B, // Lua_CommentatorSetSkirmishMatchmakingMode and Lua_CommentatorRequestSkirmishQueueData
    CMSG_COMPLAIN,                               // = 0x3C7,
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT,             // = 0x46E,
    CMSG_COMPLETE_CINEMATIC,                     // = 0x0FC,
    CMSG_COMPLETE_MOVIE,                         // = 0x465,
    CMSG_CONNECT_TO_FAILED,                      // = 0x50E,
    CMSG_CONTROLLER_EJECT_PASSENGER,             // = 0x4A9,
    CMSG_COOLDOWN_CHEAT,                         // = 0x028,
    CMSG_CORPSE_TRANSPORT_QUERY,                 // = 0x4B6,
    CMSG_CREATEGAMEOBJECT,                       // = 0x014,
    CMSG_CREATEITEM,                             // = 0x013,
    CMSG_CREATEMONSTER,                          // = 0x011,
    CMSG_DBLOOKUP,                               // = 0x002,
    CMSG_DEBUG_ACTIONS_START,                    // = 0x315,
    CMSG_DEBUG_ACTIONS_STOP,                     // = 0x316,
    CMSG_DEBUG_AISTATE,                          // = 0x02E,
    CMSG_DEBUG_CHANGECELLZONE,                   // = 0x00C,
    CMSG_DEBUG_LIST_TARGETS,                     // = 0x3D8,
    CMSG_DEBUG_PASSIVE_AURA,                     // = 0x140,
    CMSG_DEBUG_SERVER_GEO,                       // = 0x4FB,
    CMSG_DECHARGE,                               // = 0x204,
    CMSG_DECLINE_CHANNEL_INVITE,                 // = 0x410,
    CMSG_DELETEEQUIPMENT_SET,                    // = 0x13E,
    CMSG_DELETE_DANCE,                           // = 0x454,
    CMSG_DEL_PVP_MEDAL_CHEAT,                    // = 0x28A,
    CMSG_DEL_VOICE_IGNORE,                       // = 0x3DC,
    CMSG_DESTROYITEM,                            // = 0x111,
    CMSG_DESTROYMONSTER,                         // = 0x012,
    CMSG_DESTROY_ITEMS,                          // = 0x0B2,
    CMSG_DISABLE_PVP_CHEAT,                      // = 0x030,
    CMSG_DISMISS_CONTROLLED_VEHICLE,             // = 0x46D,
    CMSG_DISMISS_CRITTER,                        // = 0x48D,
    CMSG_DROP_NEW_CONNECTION,                    // = 0x513,
    CMSG_DUEL_ACCEPTED,                          // = 0x16C,
    CMSG_DUEL_CANCELLED,                         // = 0x16D,
    CMSG_DUMP_OBJECTS,                           // = 0x48B,
    CMSG_ENABLETAXI,                             // = 0x493,
    CMSG_ENABLE_DAMAGE_LOG,                      // = 0x27D,
    CMSG_END_BATTLEFIELD_CHEAT,                  // = 0x4CC,
    CMSG_EXPIRE_RAID_INSTANCE,                   // = 0x415,
    CMSG_FAR_SIGHT,                              // = 0x27A,
    CMSG_FLAG_QUEST,                             // = 0x02A,
    CMSG_FLAG_QUEST_FINISH,                      // = 0x02B,
    CMSG_FLOOD_GRACE_CHEAT,                      // = 0x497,
    CMSG_FORCEACTION,                            // = 0x018,
    CMSG_FORCEACTIONONOTHER,                     // = 0x019,
    CMSG_FORCEACTIONSHOW,                        // = 0x01A,
    CMSG_FORCE_ANIM,                             // = 0x4D7,
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK,     // = 0x384,
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK,          // = 0x382,
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK,            // = 0x45D,
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK,        // = 0x0E5,
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK,             // = 0x0E3,
    CMSG_FORCE_SAY_CHEAT,                        // = 0x47E,
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK,       // = 0x2DD,
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK,            // = 0x0E7,
    CMSG_FORCE_TURN_RATE_CHANGE_ACK,             // = 0x2DF,
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK,            // = 0x2DB,
    CMSG_GAMEOBJ_REPORT_USE,                     // = 0x481,
    CMSG_GAMEOBJ_USE,                            // = 0x0B1,
    CMSG_GAMESPEED_SET,                          // = 0x046,
    CMSG_GAMETIME_SET,                           // = 0x044,
    CMSG_GETDEATHBINDZONE,                       // = 0x156,
    CMSG_GET_CHANNEL_MEMBER_COUNT,               // = 0x3D4,
    CMSG_GET_ITEM_PURCHASE_DATA,                 // = 0x4B3,
    CMSG_GET_MAIL_LIST,                          // = 0x23A,
    CMSG_GET_MIRRORIMAGE_DATA,                   // = 0x401,
    CMSG_GHOST,                                  // = 0x1E5,
    CMSG_GMLAGREPORT_SUBMIT,                     // = 0x502,
    CMSG_GMSURVEY_SUBMIT,                        // = 0x32A,
    CMSG_GMTICKETSYSTEM_TOGGLE,                  // = 0x29A,
    CMSG_GMTICKET_CREATE,                        // = 0x205,
    CMSG_GMTICKET_DELETETICKET,                  // = 0x217,
    CMSG_GMTICKET_GETTICKET,                     // = 0x211,
    CMSG_GMTICKET_RESOLVE_RESPONSE,              // = 0x4F0,
    CMSG_GMTICKET_SYSTEMSTATUS,                  // = 0x21A,
    CMSG_GMTICKET_UPDATETEXT,                    // = 0x207,
    CMSG_GM_CHARACTER_RESTORE,                   // = 0x3FA,
    CMSG_GM_CHARACTER_SAVE,                      // = 0x3FB,
    CMSG_GM_CREATE_ITEM_TARGET,                  // = 0x210,
    CMSG_GM_CREATE_TICKET_RESPONSE,              // = 0x4F3,
    CMSG_GM_DESTROY_ONLINE_CORPSE,               // = 0x311,
    CMSG_GM_FREEZE,                              // = 0x22D,
    CMSG_GM_GRANT_ACHIEVEMENT,                   // = 0x4C4,
    CMSG_GM_INVIS,                               // = 0x1E6,
    CMSG_GM_MOVECORPSE,                          // = 0x22C,
    CMSG_GM_NUKE,                                // = 0x1FA,
    CMSG_GM_NUKE_ACCOUNT,                        // = 0x30F,
    CMSG_GM_NUKE_CHARACTER,                      // = 0x507,
    CMSG_GM_REMOVE_ACHIEVEMENT,                  // = 0x4C5,
    CMSG_GM_REQUEST_PLAYER_INFO,                 // = 0x22F,
    CMSG_GM_RESURRECT,                           // = 0x22A,
    CMSG_GM_REVEALTO,                            // = 0x229,
    CMSG_GM_SET_CRITERIA_FOR_PLAYER,             // = 0x4C6,
    CMSG_GM_SET_SECURITY_GROUP,                  // = 0x1F9,
    CMSG_GM_SHOW_COMPLAINTS,                     // = 0x3CA,
    CMSG_GM_SILENCE,                             // = 0x228,
    CMSG_GM_SUMMONMOB,                           // = 0x22B,
    CMSG_GM_TEACH,                               // = 0x20F,
    CMSG_GM_UBERINVIS,                           // = 0x22E,
    CMSG_GM_UNSQUELCH,                           // = 0x3CB,
    CMSG_GM_UNTEACH,                             // = 0x2E5,
    CMSG_GM_UPDATE_TICKET_STATUS,                // = 0x327,
    CMSG_GM_VISION,                              // = 0x226,
    CMSG_GM_WHISPER,                             // = 0x3B2,
    CMSG_GODMODE,                                // = 0x022,
    CMSG_GRANT_LEVEL,                            // = 0x40D,
    CMSG_GROUP_ACCEPT,                           // = 0x072,
    CMSG_GROUP_ASSISTANT_LEADER,                 // = 0x28F,
    CMSG_GROUP_CANCEL,                           // = 0x070,
    CMSG_GROUP_CHANGE_SUB_GROUP,                 // = 0x27E,
    CMSG_GROUP_DECLINE,                          // = 0x073,
    CMSG_GROUP_DISBAND,                          // = 0x07B,
    CMSG_GROUP_RAID_CONVERT,                     // = 0x28E,
    CMSG_GROUP_SWAP_SUB_GROUP,                   // = 0x280,
    CMSG_GROUP_UNINVITE,                         // = 0x075,
    CMSG_GROUP_UNINVITE_GUID,                    // = 0x076,
    CMSG_GUILD_ACCEPT,                           // = 0x084,
    CMSG_GUILD_BANKER_ACTIVATE,                  // = 0x3E6,
    CMSG_GUILD_BANK_DEPOSIT_MONEY,               // = 0x3EC,
    CMSG_GUILD_BANK_QUERY_TAB,                   // = 0x3E7,
    CMSG_GUILD_BANK_SWAP_ITEMS,                  // = 0x3E9,
    CMSG_GUILD_BANK_UPDATE_TAB,                  // = 0x3EB,
    CMSG_GUILD_BANK_WITHDRAW_MONEY,              // = 0x3ED,
    CMSG_GUILD_CREATE,                           // = 0x081,
    CMSG_GUILD_DECLINE,                          // = 0x085,
    CMSG_GUILD_DEMOTE,                           // = 0x08C,
    CMSG_GUILD_DISBAND,                          // = 0x08F,
    CMSG_GUILD_INVITE,                           // = 0x082,
    CMSG_GUILD_LEADER,                           // = 0x090,
    CMSG_GUILD_PROMOTE,                          // = 0x08B,
    CMSG_GUILD_REMOVE,                           // = 0x08E,
    CMSG_GUILD_SET_OFFICER_NOTE,                 // = 0x235,
    CMSG_GUILD_SET_PUBLIC_NOTE,                  // = 0x234,
    CMSG_HEARTH_AND_RESURRECT,                   // = 0x49C,
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT,       // = 0x405,
    CMSG_IGNORE_KNOCKBACK_CHEAT,                 // = 0x32C,
    CMSG_IGNORE_REQUIREMENTS_CHEAT,              // = 0x3A8,
    CMSG_INSPECT,                                // = 0x114,
    CMSG_INSTANCE_LOCK_RESPONSE,                 // = 0x13F,
    CMSG_ITEM_PURCHASE_REFUND,                   // = 0x4B4,
    CMSG_LEARN_DANCE_MOVE,                       // = 0x456,
    CMSG_LEARN_SPELL,                            // = 0x010,
    CMSG_LEARN_TALENT_GROUP,                     // = 0x4C1,
    CMSG_LEAVE_BATTLEFIELD,                      // = 0x2E1,
    CMSG_LEAVE_CHANNEL,                          // = 0x098,
    CMSG_LEVEL_CHEAT,                            // = 0x025,
    CMSG_LFG_BOOT_PLAYER_VOTE,                   // = 0x36C,
    CMSG_LFG_GET_PARTY_INFO,                     // = 0x371,
    CMSG_LFG_GET_PLAYER_INFO,                    // = 0x36E,
    CMSG_LFG_GET_STATUS,                         // = 0x296,
    CMSG_LFG_LEAVE,                              // = 0x35D,
    CMSG_LFG_PROPOSAL_RESPONSE,                  // = 0x362,
    CMSG_LFG_SEARCH_JOIN,                        // = 0x35E,
    CMSG_LFG_SEARCH_LEAVE,                       // = 0x35F,
    CMSG_LFG_SET_NEEDS,                          // = 0x36B,
    CMSG_LFG_SET_ROLES,                          // = 0x36A,
    CMSG_LFG_TELEPORT,                           // = 0x370,
    CMSG_LOAD_DANCES,                            // = 0x44D,
    CMSG_LOOT,                                   // = 0x15D,
    CMSG_LOOT_MASTER_GIVE,                       // = 0x2A3,
    CMSG_LOOT_METHOD,                            // = 0x07A,
    CMSG_LOOT_MONEY,                             // = 0x15E,
    CMSG_LOOT_RELEASE,                           // = 0x15F,
    CMSG_LOOT_ROLL,                              // = 0x2A0,
    CMSG_LOTTERY_QUERY_OBSOLETE,                 // = 0x334,
    CMSG_LOW_LEVEL_RAID,                         // = 0x508,
    CMSG_LOW_LEVEL_RAID_USER,                    // = 0x509,
    CMSG_LUA_USAGE,                              // = 0x323,
    CMSG_MAELSTROM_GM_SENT_MAIL,                 // = 0x395,
    CMSG_MAELSTROM_INVALIDATE_CACHE,             // = 0x387,
    CMSG_MAELSTROM_RENAME_GUILD,                 // = 0x400,
    CMSG_MAIL_CREATE_TEXT_ITEM,                  // = 0x24A,
    CMSG_MAIL_DELETE,                            // = 0x249,
    CMSG_MAIL_MARK_AS_READ,                      // = 0x247,
    CMSG_MAIL_RETURN_TO_SENDER,                  // = 0x248,
    CMSG_MAIL_TAKE_ITEM,                         // = 0x246,
    CMSG_MAIL_TAKE_MONEY,                        // = 0x245,
    CMSG_MAKEMONSTERATTACKGUID,                  // = 0x016,
    CMSG_MINIGAME_MOVE,                          // = 0x2F8,
    CMSG_MOUNTSPECIAL_ANIM,                      // = 0x171,
    CMSG_MOVE_CHARACTER_CHEAT,                   // = 0x00D,
    CMSG_MOVE_CHARM_PORT_CHEAT,                  // = 0x0E0,
    CMSG_MOVE_CHNG_TRANSPORT,                    // = 0x38D,
    CMSG_MOVE_FALL_RESET,                        // = 0x2CA,
    CMSG_MOVE_FEATHER_FALL_ACK,                  // = 0x2CF,
    CMSG_MOVE_GRAVITY_DISABLE_ACK,               // = 0x4CF,
    CMSG_MOVE_GRAVITY_ENABLE_ACK,                // = 0x4D1,
    CMSG_MOVE_HOVER_ACK,                         // = 0x0F6,
    CMSG_MOVE_KNOCK_BACK_ACK,                    // = 0x0F0,
    CMSG_MOVE_NOT_ACTIVE_MOVER,                  // = 0x2D1,
    CMSG_MOVE_SET_CAN_FLY_ACK,                   // = 0x345,
    CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK, // = 0x340,
    CMSG_MOVE_SET_COLLISION_HGT_ACK,             // = 0x517,
    CMSG_MOVE_SET_FLY,                           // = 0x346,
    CMSG_MOVE_SET_RAW_POSITION,                  // = 0x0E1,
    CMSG_MOVE_SET_RUN_SPEED,                     // = 0x3AB,
    CMSG_MOVE_SPLINE_DONE,                       // = 0x2C9,
    CMSG_MOVE_START_SWIM_CHEAT,                  // = 0x2D8,
    CMSG_MOVE_STOP_SWIM_CHEAT,                   // = 0x2D9,
    CMSG_MOVE_WATER_WALK_ACK,                    // = 0x2D0,
    CMSG_NEW_SPELL_SLOT,                         // = 0x12D,
    CMSG_NEXT_CINEMATIC_CAMERA,                  // = 0x0FB,
    CMSG_NO_SPELL_VARIANCE,                      // = 0x416,
    CMSG_OFFER_PETITION,                         // = 0x1C3,
    CMSG_ON_MISSILE_TRAJECTORY_COLLISION,        // = 0x4BE,
    CMSG_OPEN_ITEM,                              // = 0x0AC,
    CMSG_OPT_OUT_OF_LOOT,                        // = 0x409,
    CMSG_PARTY_SILENCE,                          // = 0x3DD,
    CMSG_PARTY_UNSILENCE,                        // = 0x3DE,
    CMSG_PERFORM_ACTION_SET,                     // = 0x14C,
    CMSG_PETGODMODE,                             // = 0x01C,
    CMSG_PETITION_BUY,                           // = 0x1BD,
    CMSG_PETITION_SHOWLIST,                      // = 0x1BB,
    CMSG_PETITION_SHOW_SIGNATURES,               // = 0x1BE,
    CMSG_PETITION_SIGN,                          // = 0x1C0,
    CMSG_PET_ABANDON,                            // = 0x176,
    CMSG_PET_ACTION,                             // = 0x175,
    CMSG_PET_CANCEL_AURA,                        // = 0x26B,
    CMSG_PET_CAST_SPELL,                         // = 0x1F0,
    CMSG_PET_LEARN_TALENT,                       // = 0x47A,
    CMSG_PET_LEARN_TALENT_GROUP,                 // = 0x4C2,
    CMSG_PET_LEVEL_CHEAT,                        // = 0x026,
    CMSG_PET_RENAME,                             // = 0x177,
    CMSG_PET_SET_ACTION,                         // = 0x174,
    CMSG_PET_SPELL_AUTOCAST,                     // = 0x2F3,
    CMSG_PET_STOP_ATTACK,                        // = 0x2EA,
    CMSG_PET_UNLEARN,                            // = 0x2F0,
    CMSG_PET_UNLEARN_TALENTS,                    // = 0x47B,
    CMSG_PLAYER_AI_CHEAT,                        // = 0x26C,
    CMSG_PLAY_DANCE,                             // = 0x44B,
    CMSG_PROFILEDATA_REQUEST,                    // = 0x4C9,
    CMSG_PUSHQUESTTOPARTY,                       // = 0x19D,
    CMSG_PVP_QUEUE_STATS_REQUEST,                // = 0x4DB,
    CMSG_QUERY_GET_ALL_QUESTS,                   // = 0x500,
    CMSG_QUERY_OBJECT_POSITION,                  // = 0x004,
    CMSG_QUERY_OBJECT_ROTATION,                  // = 0x006,
    CMSG_QUERY_SERVER_BUCK_DATA,                 // = 0x41B,
    CMSG_QUERY_VEHICLE_STATUS,                   // = 0x4A5,
    CMSG_QUESTGIVER_CANCEL,                      // = 0x190,
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH,            // = 0x187,
    CMSG_QUESTLOG_SWAP_QUEST,                    // = 0x193,
    CMSG_READ_ITEM,                              // = 0x0AD,
    CMSG_RECHARGE,                               // = 0x00F,
    CMSG_RECLAIM_CORPSE,                         // = 0x1D2,
    CMSG_REFER_A_FRIEND,                         // = 0x40E,
    CMSG_REMOVE_GLYPH,                           // = 0x48A,
    CMSG_REPAIR_ITEM,                            // = 0x2A8,
    CMSG_REPOP_REQUEST,                          // = 0x15A,
    CMSG_REPORT_PVP_AFK,                         // = 0x3E4,
    CMSG_REQUEST_PARTY_MEMBER_STATS,             // = 0x27F,
    CMSG_REQUEST_PET_INFO,                       // = 0x279,
    CMSG_REQUEST_VEHICLE_EXIT,                   // = 0x476,
    CMSG_REQUEST_VEHICLE_NEXT_SEAT,              // = 0x478,
    CMSG_REQUEST_VEHICLE_PREV_SEAT,              // = 0x477,
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT,            // = 0x479,
    CMSG_RESET_FACTION_CHEAT,                    // = 0x281,
    CMSG_RESET_INSTANCES,                        // = 0x31D,
    CMSG_RESURRECT_RESPONSE,                     // = 0x15C,
    CMSG_RIDE_VEHICLE_INTERACT,                  // = 0x4A8,
    CMSG_RUN_SCRIPT,                             // = 0x2B5,
    CMSG_SAVE_DANCE,                             // = 0x449,
    CMSG_SAVE_EQUIPMENT_SET,                     // = 0x4BD,
    CMSG_SAVE_PLAYER,                            // = 0x153,
    CMSG_SELF_RES,                               // = 0x2B3,
    CMSG_SELL_ITEM,                              // = 0x1A0,
    CMSG_SEND_COMBAT_TRIGGER,                    // = 0x394,
    CMSG_SEND_EVENT,                             // = 0x02D,
    CMSG_SEND_GENERAL_TRIGGER,                   // = 0x393,
    CMSG_SEND_LOCAL_EVENT,                       // = 0x392,
    CMSG_SEND_MAIL,                              // = 0x238,
    CMSG_SERVERINFO,                             // = 0x4F4,
    CMSG_SERVERTIME,                             // = 0x048,
    CMSG_SERVER_BROADCAST,                       // = 0x2B2,
    CMSG_SERVER_COMMAND,                         // = 0x227,
    CMSG_SERVER_INFO_QUERY,                      // = 0x4A0,
    CMSG_SETDEATHBINDPOINT,                      // = 0x154,
    CMSG_SETSHEATHED,                            // = 0x1E0,
    CMSG_SET_ACTIVE_MOVER,                       // = 0x26A,
    CMSG_SET_ACTIVE_TALENT_GROUP_OBSOLETE,       // = 0x4C3,
    CMSG_SET_ACTIVE_VOICE_CHANNEL,               // = 0x3D3,
    CMSG_SET_AMMO,                               // = 0x268,
    CMSG_SET_ARENA_MEMBER_SEASON_GAMES,          // = 0x4B1,
    CMSG_SET_ARENA_MEMBER_WEEKLY_GAMES,          // = 0x4B0,
    CMSG_SET_ARENA_TEAM_RATING_BY_INDEX,         // = 0x4AD,
    CMSG_SET_ARENA_TEAM_SEASON_GAMES,            // = 0x4AF,
    CMSG_SET_ARENA_TEAM_WEEKLY_GAMES,            // = 0x4AE,
    CMSG_SET_BREATH,                             // = 0x4A4,
    CMSG_SET_CHANNEL_WATCH,                      // = 0x3EF,
    CMSG_SET_CHARACTER_MODEL,                    // = 0x50C,
    CMSG_SET_CRITERIA_CHEAT,                     // = 0x470,
    CMSG_SET_DURABILITY_CHEAT,                   // = 0x287,
    CMSG_SET_EXPLORATION,                        // = 0x2BE,
    CMSG_SET_EXPLORATION_ALL,                    // = 0x31B,
    CMSG_SET_FACTION_ATWAR,                      // = 0x125,
    CMSG_SET_FACTION_CHEAT,                      // = 0x126,
    CMSG_SET_FACTION_INACTIVE,                   // = 0x317,
    CMSG_SET_GLYPH,                              // = 0x467,
    CMSG_SET_GLYPH_SLOT,                         // = 0x466,
    CMSG_SET_GRANTABLE_LEVELS,                   // = 0x40C,
    CMSG_SET_GUILD_BANK_TEXT,                    // = 0x40B,
    CMSG_SET_LFG_COMMENT,                        // = 0x366,
    CMSG_SET_PAID_SERVICE_CHEAT,                 // = 0x4DD,
    CMSG_SET_PLAYER_DECLINED_NAMES,              // = 0x419,
    CMSG_SET_PVP_RANK_CHEAT,                     // = 0x288,
    CMSG_SET_PVP_TITLE,                          // = 0x28B,
    CMSG_SET_RUNE_COOLDOWN,                      // = 0x459,
    CMSG_SET_RUNE_COUNT,                         // = 0x458,
    CMSG_SET_SAVED_INSTANCE_EXTEND,              // = 0x292,
    CMSG_SET_SKILL_CHEAT,                        // = 0x1D8,
    CMSG_SET_STAT_CHEAT,                         // = 0x21D,
    CMSG_SET_TAXI_BENCHMARK_MODE,                // = 0x389,
    CMSG_SET_TITLE,                              // = 0x374,
    CMSG_SET_TITLE_SUFFIX,                       // = 0x3F7,
    CMSG_SET_VEHICLE_REC_ID_ACK,                 // = 0x240,
    CMSG_SET_WATCHED_FACTION,                    // = 0x318,
    CMSG_SET_WORLDSTATE,                         // = 0x027,
    CMSG_SHOWING_CLOAK,                          // = 0x2BA,
    CMSG_SHOWING_HELM,                           // = 0x2B9,
    CMSG_SKILL_BUY_RANK,                         // = 0x220,
    CMSG_SKILL_BUY_STEP,                         // = 0x21F,
    CMSG_SOCKET_GEMS,                            // = 0x347,
    CMSG_SPELLCLICK,                             // = 0x3F8,
    CMSG_SPLIT_ITEM,                             // = 0x10E,
    CMSG_STABLE_PET,                             // = 0x270,
    CMSG_STABLE_REVIVE_PET,                      // = 0x274,
    CMSG_STABLE_SWAP_PET,                        // = 0x275,
    CMSG_START_BATTLEFIELD_CHEAT,                // = 0x4CB,
    CMSG_START_QUEST,                            // = 0x489,
    CMSG_STOP_DANCE,                             // = 0x44E,
    CMSG_STORE_LOOT_IN_SLOT,                     // = 0x109,
    CMSG_SUMMON_RESPONSE,                        // = 0x2AC,
    CMSG_SUSPEND_COMMS_ACK,                      // = 0x510,
    CMSG_SYNC_DANCE,                             // = 0x450,
    CMSG_TARGET_CAST,                            // = 0x3D0,
    CMSG_TARGET_SCRIPT_CAST,                     // = 0x3D1,
    CMSG_TAXICLEARALLNODES,                      // = 0x1A6,
    CMSG_TAXICLEARNODE,                          // = 0x241,
    CMSG_TAXIENABLEALLNODES,                     // = 0x1A7,
    CMSG_TAXIENABLENODE,                         // = 0x242,
    CMSG_TAXINODE_STATUS_QUERY,                  // = 0x1AA,
    CMSG_TAXIQUERYAVAILABLENODES,                // = 0x1AC,
    CMSG_TAXISHOWNODES,                          // = 0x1A8,
    CMSG_TELEPORT_TO_UNIT,                       // = 0x009,
    CMSG_TEST_DROP_RATE,                         // = 0x294,
    CMSG_TIME_SYNC_RESP,                         // = 0x391,
    CMSG_TOGGLE_PVP,                             // = 0x253,
    CMSG_TOTEM_DESTROYED,                        // = 0x414,
    CMSG_TRIGGER_CINEMATIC_CHEAT,                // = 0x0F8,
    CMSG_TURN_IN_PETITION,                       // = 0x1C4,
    CMSG_TUTORIAL_CLEAR,                         // = 0x0FF,
    CMSG_TUTORIAL_RESET,                         // = 0x100,
    CMSG_UNCLAIM_LICENSE,                        // = 0x110,
    CMSG_UNDRESSPLAYER,                          // = 0x020,
    CMSG_UNITANIMTIER_CHEAT,                     // = 0x472,
    CMSG_UNKNOWN_1320,                           // = 0x528, // setcurrency console command?
    CMSG_UNLEARN_DANCE_MOVE,                     // = 0x457,
    CMSG_UNLEARN_SKILL,                          // = 0x202,
    CMSG_UNLEARN_SPELL,                          // = 0x201,
    CMSG_UNLEARN_TALENTS,                        // = 0x213,
    CMSG_UNSTABLE_PET,                           // = 0x271,
    CMSG_UNUSED5,                                // = 0x4B8,
    CMSG_UNUSED6,                                // = 0x4B9,
    CMSG_UPDATE_MISSILE_TRAJECTORY,              // = 0x462,
    CMSG_USE_EQUIPMENT_SET,                      // = 0x4D5,
    CMSG_USE_ITEM,                               // = 0x0AB,
    CMSG_USE_SKILL_CHEAT,                        // = 0x029,
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST,         // = 0x3A1,
    CMSG_WARDEN_DATA,                            // = 0x2E7,
    CMSG_WEATHER_SPEED_CHEAT,                    // = 0x01F,
    CMSG_WRAP_ITEM,                              // = 0x1D3,
    CMSG_XPGAIN,                                 // = 0x4EC,
    CMSG_XP_CHEAT,                               // = 0x221,
    CMSG_ZONE_MAP,                               // = 0x00A,
    MSG_AUCTION_HELLO,                           // = 0x255,
    MSG_BATTLEGROUND_PLAYER_POSITIONS,           // = 0x2E9,
    MSG_CHANNEL_START,                           // = 0x139,
    MSG_CHANNEL_UPDATE,                          // = 0x13A,
    MSG_CORPSE_QUERY,                            // = 0x216,
    MSG_DELAY_GHOST_TELEPORT,                    // = 0x32E,
    MSG_DEV_SHOWLABEL,                           // = 0x2AD,
    MSG_GM_ACCOUNT_ONLINE,                       // = 0x26E,
    MSG_GM_BIND_OTHER,                           // = 0x1E8,
    MSG_GM_CHANGE_ARENA_RATING,                  // = 0x40F,
    MSG_GM_DESTROY_CORPSE,                       // = 0x310,
    MSG_GM_GEARRATING,                           // = 0x3B4,
    MSG_GM_RESETINSTANCELIMIT,                   // = 0x33C,
    MSG_GM_SHOWLABEL,                            // = 0x1EF,
    MSG_GM_SUMMON,                               // = 0x1E9,
    MSG_GUILD_BANK_LOG_QUERY,                    // = 0x3EE,
    MSG_GUILD_BANK_MONEY_WITHDRAWN,              // = 0x3FE,
    MSG_GUILD_EVENT_LOG_QUERY,                   // = 0x3FF,
    MSG_GUILD_PERMISSIONS,                       // = 0x3FD,
    MSG_INSPECT_ARENA_TEAMS,                     // = 0x377,
    MSG_INSPECT_HONOR_STATS,                     // = 0x2D6,
    MSG_LIST_STABLED_PETS,                       // = 0x26F,
    MSG_MINIMAP_PING,                            // = 0x1D5,
    MSG_MOVE_FEATHER_FALL,                       // = 0x2B0,
    MSG_MOVE_GRAVITY_CHNG,                       // = 0x4D2,
    MSG_MOVE_HOVER,                              // = 0x0F7,
    MSG_MOVE_KNOCK_BACK,                         // = 0x0F1,
    MSG_MOVE_ROOT,                               // = 0x0EC,
    MSG_MOVE_SET_ALL_SPEED_CHEAT,                // = 0x0D6,
    MSG_MOVE_SET_COLLISION_HGT,                  // = 0x518,
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT,        // = 0x37F,
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT,             // = 0x37D,
    MSG_MOVE_SET_PITCH_RATE_CHEAT,               // = 0x45A,
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT,           // = 0x0CE,
    MSG_MOVE_SET_RUN_MODE,                       // = 0x0C2,
    MSG_MOVE_SET_RUN_SPEED_CHEAT,                // = 0x0CC,
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT,          // = 0x0D4,
    MSG_MOVE_SET_SWIM_SPEED_CHEAT,               // = 0x0D2,
    MSG_MOVE_SET_TURN_RATE_CHEAT,                // = 0x0D7,
    MSG_MOVE_SET_WALK_MODE,                      // = 0x0C3,
    MSG_MOVE_SET_WALK_SPEED_CHEAT,               // = 0x0D0,
    MSG_MOVE_START_SWIM_CHEAT,                   // = 0x341,
    MSG_MOVE_STOP_SWIM_CHEAT,                    // = 0x342,
    MSG_MOVE_TELEPORT_CHEAT,                     // = 0x0C6,
    MSG_MOVE_TIME_SKIPPED,                       // = 0x319,
    MSG_MOVE_TOGGLE_COLLISION_CHEAT,             // = 0x0D9,
    MSG_MOVE_TOGGLE_FALL_LOGGING,                // = 0x0C8,
    MSG_MOVE_TOGGLE_LOGGING,                     // = 0x0C4,
    MSG_MOVE_UNROOT,                             // = 0x0ED,
    MSG_MOVE_UPDATE_CAN_FLY,                     // = 0x3AD,
    MSG_MOVE_UPDATE_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, // = 0x34A,
    MSG_MOVE_WATER_WALK,                         // = 0x2B1,
    MSG_NOTIFY_PARTY_SQUELCH,                    // = 0x3DF,
    MSG_NULL_ACTION,                             // = 0x000,
    MSG_PARTY_ASSIGNMENT,                        // = 0x38E,
    MSG_PETITION_DECLINE,                        // = 0x1C2,
    MSG_PETITION_RENAME,                         // = 0x2C1,
    MSG_PVP_LOG_DATA,                            // = 0x2E0,
    MSG_QUERY_GUILD_BANK_TEXT,                   // = 0x40A,
    MSG_QUEST_PUSH_RESULT,                       // = 0x276,
    MSG_RAID_READY_CHECK,                        // = 0x322,
    MSG_RAID_READY_CHECK_CONFIRM,                // = 0x3AE,
    MSG_RAID_READY_CHECK_FINISHED,               // = 0x3C6,
    MSG_RAID_TARGET_UPDATE,                      // = 0x321,
    MSG_RANDOM_ROLL,                             // = 0x1FB,
    MSG_SAVE_GUILD_EMBLEM,                       // = 0x1F1,
    MSG_SET_RAID_DIFFICULTY,                     // = 0x4EB,
    MSG_TABARDVENDOR_ACTIVATE,                   // = 0x1F2,
    MSG_VIEW_PHASE_SHIFT,                        // = 0x4F9,
    SMSG_ACTIVATETAXIREPLY,                      // = 0x1AE,
    SMSG_ADD_RUNE_POWER,                         // = 0x488,
    SMSG_AFK_MONITOR_INFO_RESPONSE,              // = 0x504,
    SMSG_AI_REACTION,                            // = 0x13C,
    SMSG_ALL_QUESTS_COMPLETED,                   // = 0x501,
    SMSG_AREA_SPIRIT_HEALER_TIME,                // = 0x2E4,
    SMSG_AREA_TRIGGER_MESSAGE,                   // = 0x2B8,
    SMSG_AREA_TRIGGER_NO_CORPSE,                 // = 0x506,
    SMSG_ARENA_ERROR,                            // = 0x376,
    SMSG_ARENA_TEAM_CHANGE_FAILED,               // = 0x4C8,
    SMSG_ARENA_TEAM_COMMAND_RESULT,              // = 0x349,
    SMSG_ARENA_TEAM_EVENT,                       // = 0x357,
    SMSG_ARENA_TEAM_INVITE,                      // = 0x350,
    SMSG_AUCTION_BIDDER_LIST_RESULT,             // = 0x265,
    SMSG_AUCTION_BIDDER_NOTIFICATION,            // = 0x25E,
    SMSG_AUCTION_LIST_PENDING_SALES,             // = 0x490,
    SMSG_AUCTION_LIST_RESULT,                    // = 0x25C,
    SMSG_AUCTION_OWNER_LIST_RESULT,              // = 0x25D,
    SMSG_AUCTION_OWNER_NOTIFICATION,             // = 0x25F,
    SMSG_AURACASTLOG,                            // = 0x1D1,
    SMSG_AUTH_SRP6_RESPONSE,                     // = 0x039,
    SMSG_AVAILABLE_VOICE_CHANNEL,                // = 0x3DA,
    SMSG_BATTLEFIELD_MANAGER_EJECTED,            // = 0x4E6,
    SMSG_BATTLEFIELD_MANAGER_EJECT_PENDING,      // = 0x4E5,
    SMSG_BATTLEFIELD_MANAGER_STATE_CHANGED,      // = 0x4E8,
    SMSG_BATTLEFIELD_STATUS,                     // = 0x2D4,
    SMSG_BATTLEGROUND_INFO_THROTTLED,            // = 0x4A6,
    SMSG_BATTLEGROUND_PLAYER_JOINED,             // = 0x2EC,
    SMSG_BATTLEGROUND_PLAYER_LEFT,               // = 0x2ED,
    SMSG_BINDER_CONFIRM,                         // = 0x2EB,
    SMSG_BINDZONEREPLY,                          // = 0x157,
    SMSG_BREAK_TARGET,                           // = 0x152,
    SMSG_BUY_BANK_SLOT_RESULT,                   // = 0x1BA,
    SMSG_BUY_FAILED,                             // = 0x1A5,
    SMSG_BUY_ITEM,                               // = 0x1A4,
    SMSG_CALENDAR_ARENA_TEAM,                    // = 0x439,
    SMSG_CALENDAR_CLEAR_PENDING_ACTION,          // = 0x4BB,
    SMSG_CALENDAR_COMMAND_RESULT,                // = 0x43D,
    SMSG_CALENDAR_EVENT_INVITE,                  // = 0x43A,
    SMSG_CALENDAR_EVENT_INVITE_ALERT,            // = 0x440,
    SMSG_CALENDAR_EVENT_INVITE_NOTES,            // = 0x460,
    SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT,      // = 0x461,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED,          // = 0x43B,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT,    // = 0x441,
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT,     // = 0x442,
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT,  // = 0x445,
    SMSG_CALENDAR_EVENT_REMOVED_ALERT,           // = 0x443,
    SMSG_CALENDAR_EVENT_STATUS,                  // = 0x43C,
    SMSG_CALENDAR_EVENT_UPDATED_ALERT,           // = 0x444,
    SMSG_CALENDAR_FILTER_GUILD,                  // = 0x438,
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED,            // = 0x43E,
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED,          // = 0x43F,
    SMSG_CALENDAR_RAID_LOCKOUT_UPDATED,          // = 0x471,
    SMSG_CALENDAR_SEND_CALENDAR,                 // = 0x436,
    SMSG_CALENDAR_SEND_EVENT,                    // = 0x437,
    SMSG_CALENDAR_SEND_NUM_PENDING,              // = 0x448,
    SMSG_CAMERA_SHAKE,                           // = 0x50A,
    SMSG_CANCEL_AUTO_REPEAT,                     // = 0x29C,
    SMSG_CANCEL_COMBAT,                          // = 0x14E,
    SMSG_CHANGEPLAYER_DIFFICULTY_RESULT,         // = 0x20E,
    SMSG_CHARACTER_LOGIN_FAILED,                 // = 0x041,
    SMSG_CHARACTER_PROFILE,                      // = 0x338,
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED,      // = 0x339,
    SMSG_CHAR_CUSTOMIZE,                         // = 0x474,
    SMSG_CHAR_FACTION_CHANGE,                    // = 0x4DA,
    SMSG_CHAR_RENAME,                            // = 0x2C8,
    SMSG_CHAT_NOT_IN_PARTY,                      // = 0x299,
    SMSG_CHAT_PLAYER_AMBIGUOUS,                  // = 0x32D,
    SMSG_CHAT_PLAYER_NOT_FOUND,                  // = 0x2A9,
    SMSG_CHAT_RESTRICTED,                        // = 0x2FD,
    SMSG_CHAT_WRONG_FACTION,                     // = 0x219,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE,   // = 0x39B,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE, // = 0x39C,
    SMSG_CHEAT_PLAYER_LOOKUP,                    // = 0x3C4,
    SMSG_CHECK_FOR_BOTS,                         // = 0x015,
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE,         // = 0x3A6,
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE,              // = 0x20D,
    SMSG_CLIENT_CONTROL_UPDATE,                  // = 0x159,
    SMSG_COMMENTATOR_GET_PLAYER_INFO,            // = 0x3BA,
    SMSG_COMMENTATOR_MAP_INFO,                   // = 0x3B8,
    SMSG_COMMENTATOR_PLAYER_INFO,                // = 0x3BB,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1,     // = 0x51C, // event EVENT_COMMENTATOR_SKIRMISH_QUEUE_REQUEST, CGCommentator::QueueNode
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2,     // = 0x51D, // event EVENT_COMMENTATOR_SKIRMISH_QUEUE_REQUEST
    SMSG_COMMENTATOR_STATE_CHANGED,              // = 0x3B6,
    SMSG_COMPLAIN_RESULT,                        // = 0x3C8,
    SMSG_COMPOUND_MOVE,                          // = 0x4CD,
    SMSG_COMPRESSED_MOVES,                       // = 0x2FB,
    SMSG_COMPRESSED_UNKNOWN_1310,                // = 0x51E, // some compressed packet
    SMSG_COMSAT_DISCONNECT,                      // = 0x3E1,
    SMSG_COMSAT_RECONNECT_TRY,                   // = 0x3E0,
    SMSG_CONNECT_TO,                             // = 0x50D,
    SMSG_CONVERT_RUNE,                           // = 0x486,
    SMSG_COOLDOWN_CHEAT,                         // = 0x1E1,
    SMSG_COOLDOWN_EVENT,                         // = 0x135,
    SMSG_CORPSE_TRANSPORT_QUERY,                 // = 0x4B7,
    SMSG_CROSSED_INEBRIATION_THRESHOLD,          // = 0x3C1,
    SMSG_DAMAGE_CALC_LOG,                        // = 0x27C,
    SMSG_DBLOOKUP,                               // = 0x003,
    SMSG_DEATH_RELEASE_LOC,                      // = 0x378,
    SMSG_DEBUGAURAPROC,                          // = 0x24D,
    SMSG_DEBUG_AISTATE,                          // = 0x02F,
    SMSG_DEBUG_LIST_TARGETS,                     // = 0x3D9,
    SMSG_DEBUG_SERVER_GEO,                       // = 0x4FC,
    SMSG_DISMOUNT,                               // = 0x3AC,
    SMSG_DISMOUNTRESULT,                         // = 0x16F,
    SMSG_DUEL_INBOUNDS,                          // = 0x169,
    SMSG_DUEL_OUTOFBOUNDS,                       // = 0x168,
    SMSG_DUMP_OBJECTS_DATA,                      // = 0x48C,
    SMSG_DYNAMIC_DROP_ROLL_RESULT,               // = 0x469,
    SMSG_ECHO_PARTY_SQUELCH,                     // = 0x3F6,
    SMSG_EXPECTED_SPAM_RECORDS,                  // = 0x332,
    SMSG_EXPLORATION_EXPERIENCE,                 // = 0x1F8,
    SMSG_FEIGN_DEATH_RESISTED,                   // = 0x2B4,
    SMSG_FISH_ESCAPED,                           // = 0x1C9,
    SMSG_FISH_NOT_HOOKED,                        // = 0x1C8,
    SMSG_FORCEACTIONSHOW,                        // = 0x01B,
    SMSG_FORCED_DEATH_UPDATE,                    // = 0x37A,
    SMSG_FORCE_ANIM,                             // = 0x4D8,
    SMSG_FORCE_DISPLAY_UPDATE,                   // = 0x403,
    SMSG_FORCE_SET_VEHICLE_REC_ID,               // = 0x23F,
    SMSG_GAMEOBJECT_CUSTOM_ANIM,                 // = 0x0B3,
    SMSG_GAMEOBJECT_DESPAWN_ANIM,                // = 0x215,
    SMSG_GAMEOBJECT_PAGETEXT,                    // = 0x1DF,
    SMSG_GAMEOBJECT_RESET_STATE,                 // = 0x2A7,
    SMSG_GAMETIMEBIAS_SET,                       // = 0x314,
    SMSG_GHOSTEE_GONE,                           // = 0x326,
    SMSG_GMTICKET_CREATE,                        // = 0x206,
    SMSG_GMTICKET_CREATE_RESPONSE_TICKET,        // = 0x4F2,
    SMSG_GMTICKET_DELETETICKET,                  // = 0x218,
    SMSG_GMTICKET_GETTICKET,                     // = 0x212,
    SMSG_GMTICKET_GET_RESPONSE,                  // = 0x4EF,
    SMSG_GMTICKET_RESOLVE_RESPONSE,              // = 0x4F1,
    SMSG_GMTICKET_RESPONSE_ERROR,                // = 0x4EE,
    SMSG_GMTICKET_SYSTEMSTATUS,                  // = 0x21B,
    SMSG_GMTICKET_UPDATETEXT,                    // = 0x208,
    SMSG_GM_MESSAGECHAT,                         // = 0x3B3,
    SMSG_GM_PLAYER_INFO,                         // = 0x230,
    SMSG_GM_TICKET_STATUS_UPDATE,                // = 0x328,
    SMSG_GODMODE,                                // = 0x023,
    SMSG_GOGOGO_OBSOLETE,                        // = 0x3F5,
    SMSG_GROUPACTION_THROTTLED,                  // = 0x411,
    SMSG_GROUP_CANCEL,                           // = 0x071,
    SMSG_GROUP_DECLINE,                          // = 0x074,
    SMSG_GROUP_DESTROYED,                        // = 0x07C,
    SMSG_GROUP_INVITE,                           // = 0x06F,
    SMSG_GROUP_JOINED_BATTLEGROUND,              // = 0x2E8,
    SMSG_GROUP_UNINVITE,                         // = 0x077,
    SMSG_GUILD_DECLINE,                          // = 0x086,
    SMSG_GUILD_INVITE,                           // = 0x083,
    SMSG_HEALTH_UPDATE,                          // = 0x47F,
    SMSG_HIGHEST_THREAT_UPDATE,                  // = 0x482,
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT,       // = 0x406,
    SMSG_IGNORE_REQUIREMENTS_CHEAT,              // = 0x3A9,
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE,          // = 0x3A3,
    SMSG_INSPECT_RESULTS,                        // = 0x3F4,
    SMSG_INSPECT_RESULTS_UPDATE,                 // = 0x115,
    SMSG_INSTANCE_ENCOUNTER,                     // = 0x214,
    SMSG_INSTANCE_SAVE_CREATED,                  // = 0x2CB,
    SMSG_INVALIDATE_DANCE,                       // = 0x453,
    SMSG_INVALIDATE_PLAYER,                      // = 0x31C,
    SMSG_INVALID_PROMOTION_CODE,                 // = 0x1E7,
    SMSG_INVENTORY_CHANGE_FAILURE,               // = 0x112,
    SMSG_ITEM_COOLDOWN,                          // = 0x0B0,
    SMSG_ITEM_ENCHANT_TIME_UPDATE,               // = 0x1EB,
    SMSG_ITEM_PURCHASE_REFUND_RESULT,            // = 0x4B5,
    SMSG_ITEM_PUSH_RESULT,                       // = 0x166,
    SMSG_ITEM_TIME_UPDATE,                       // = 0x1EA,
    SMSG_JOINED_BATTLEGROUND_QUEUE,              // = 0x38A,
    SMSG_KICK_REASON,                            // = 0x3C5,
    SMSG_LFG_PLAYER_INFO,                        // = 0x36F,
    SMSG_LFG_SEARCH_RESULTS,                     // = 0x360,
    SMSG_LOOT_ALL_PASSED,                        // = 0x29E,
    SMSG_LOOT_CLEAR_MONEY,                       // = 0x165,
    SMSG_LOOT_ITEM_NOTIFY,                       // = 0x164,
    SMSG_LOOT_LIST,                              // = 0x3F9,
    SMSG_LOOT_MASTER_LIST,                       // = 0x2A4,
    SMSG_LOOT_MONEY_NOTIFY,                      // = 0x163,
    SMSG_LOOT_RELEASE_RESPONSE,                  // = 0x161,
    SMSG_LOOT_REMOVED,                           // = 0x162,
    SMSG_LOOT_RESPONSE,                          // = 0x160,
    SMSG_LOOT_ROLL,                              // = 0x2A2,
    SMSG_LOOT_ROLL_WON,                          // = 0x29F,
    SMSG_LOOT_START_ROLL,                        // = 0x2A1,
    SMSG_LOOT_UPDATE,                            // = 0x4FD,
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE,          // = 0x335,
    SMSG_LOTTERY_RESULT_OBSOLETE,                // = 0x337,
    SMSG_MINIGAME_MOVE_FAILED,                   // = 0x2F9,
    SMSG_MIRRORIMAGE_DATA,                       // = 0x402,
    SMSG_MODIFY_COOLDOWN,                        // = 0x491,
    SMSG_MONSTER_MOVE_TRANSPORT,                 // = 0x2AE,
    SMSG_MOUNTRESULT,                            // = 0x16E,
    SMSG_MOUNTSPECIAL_ANIM,                      // = 0x172,
    SMSG_MOVE_CHARACTER_CHEAT,                   // = 0x00E,
    SMSG_MOVE_FEATHER_FALL,                      // = 0x0F2,
    SMSG_MOVE_GRAVITY_DISABLE,                   // = 0x4CE,
    SMSG_MOVE_GRAVITY_ENABLE,                    // = 0x4D0,
    SMSG_MOVE_KNOCK_BACK,                        // = 0x0EF,
    SMSG_MOVE_LAND_WALK,                         // = 0x0DF,
    SMSG_MOVE_NORMAL_FALL,                       // = 0x0F3,
    SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, // = 0x33E,
    SMSG_MOVE_SET_COLLISION_HGT,                 // = 0x516,
    SMSG_MOVE_SET_HOVER,                         // = 0x0F4,
    SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, //= 0x33F,
    SMSG_MOVE_UNSET_HOVER,                       // = 0x0F5,
    SMSG_MOVE_WATER_WALK,                        // = 0x0DE,
    SMSG_NEW_TAXI_PATH,                          // = 0x1AF,
    SMSG_NOTIFICATION,                           // = 0x1CB,
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST,             // = 0x48E,
    SMSG_NOTIFY_MISSILE_TRAJECTORY_COLLISION,    // = 0x4BF,
    SMSG_NPC_WONT_TALK,                          // = 0x181,
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA,   // = 0x49D,
    SMSG_OPEN_CONTAINER,                         // = 0x113,
    SMSG_OPEN_LFG_DUNGEON_FINDER,                // = 0x515,
    SMSG_OVERRIDE_LIGHT,                         // = 0x412,
    SMSG_PARTY_MEMBER_STATS,                     // = 0x07E,
    SMSG_PARTY_MEMBER_STATS_FULL,                // = 0x2F2,
    SMSG_PAUSE_MIRROR_TIMER,                     // = 0x1DA,
    SMSG_PENDING_RAID_LOCK,                      // = 0x147,
    SMSG_PETGODMODE,                             // = 0x01D,
    SMSG_PETITION_SHOWLIST,                      // = 0x1BC,
    SMSG_PETITION_SHOW_SIGNATURES,               // = 0x1BF,
    SMSG_PETITION_SIGN_RESULTS,                  // = 0x1C1,
    SMSG_PET_ACTION_SOUND,                       // = 0x324,
    SMSG_PET_CAST_FAILED,                        // = 0x138,
    SMSG_PET_DISMISS_SOUND,                      // = 0x325,
    SMSG_PET_LEARNED_SPELL,                      // = 0x499,
    SMSG_PET_NAME_INVALID,                       // = 0x178,
    SMSG_PET_REMOVED_SPELL,                      // = 0x49A,
    SMSG_PET_TAME_FAILURE,                       // = 0x173,
    SMSG_PET_UNLEARN_CONFIRM,                    // = 0x2F1,
    SMSG_PLAYERBINDERROR,                        // = 0x1B6,
    SMSG_PLAYERBOUND,                            // = 0x158,
    SMSG_PLAYER_SKINNED,                         // = 0x2BC,
    SMSG_PLAY_MUSIC,                             // = 0x277,
    SMSG_PLAY_OBJECT_SOUND,                      // = 0x278,
    SMSG_PLAY_TIME_WARNING,                      // = 0x2F5,
    SMSG_PRE_RESURRECT,                          // = 0x494,
    SMSG_PROFILEDATA_RESPONSE,                   // = 0x4CA,
    SMSG_PROPOSE_LEVEL_GRANT,                    // = 0x41F,
    SMSG_PVP_CREDIT,                             // = 0x28C,
    SMSG_PVP_QUEUE_STATS,                        // = 0x4DC,
    SMSG_QUERY_OBJECT_POSITION,                  // = 0x005,
    SMSG_QUERY_OBJECT_ROTATION,                  // = 0x007,
    SMSG_QUESTUPDATE_ADD_ITEM_OBSOLETE,          // = 0x19A,
    SMSG_QUESTUPDATE_ADD_KILL,                   // = 0x199,
    SMSG_QUESTUPDATE_ADD_PVP_KILL,               // = 0x46F,
    SMSG_QUESTUPDATE_COMPLETE,                   // = 0x198,
    SMSG_QUESTUPDATE_FAILED,                     // = 0x196,
    SMSG_QUESTUPDATE_FAILEDTIMER,                // = 0x197,
    SMSG_QUEST_FORCE_REMOVED,                    // = 0x21E,
    SMSG_QUEST_POI_QUERY_RESPONSE,               // = 0x1E4,
    SMSG_RAID_GROUP_ONLY,                        // = 0x286,
    SMSG_RAID_READY_CHECK_ERROR,                 // = 0x408,
    SMSG_READ_ITEM_FAILED,                       // = 0x0AF,
    SMSG_READ_ITEM_OK,                           // = 0x0AE,
    SMSG_REAL_GROUP_UPDATE,                      // = 0x397,
    SMSG_REFER_A_FRIEND_EXPIRED,                 // = 0x01E,
    SMSG_REFER_A_FRIEND_FAILURE,                 // = 0x421,
    SMSG_REMOVED_FROM_PVP_QUEUE,                 // = 0x170,
    SMSG_REPORT_PVP_AFK_RESULT,                  // = 0x3E5,
    SMSG_RESET_RANGED_COMBAT_TIMER,              // = 0x298,
    SMSG_RESISTLOG,                              // = 0x1D6,
    SMSG_RESUME_CAST_BAR,                        // = 0x14D,
    SMSG_RESUME_COMMS,                           // = 0x511,
    SMSG_RESURRECT_FAILED,                       // = 0x252,
    SMSG_RESURRECT_REQUEST,                      // = 0x15B,
    SMSG_RESYNC_RUNES,                           // = 0x487,
    SMSG_RWHOIS,                                 // = 0x1FE,
    SMSG_SCRIPT_MESSAGE,                         // = 0x2B6,
    SMSG_SELL_ITEM,                              // = 0x1A1,
    SMSG_SEND_ALL_COMBAT_LOG,                    // = 0x514,
    SMSG_SEND_MAIL_RESULT,                       // = 0x239,
    SMSG_SERVERINFO,                             // = 0x4F5,
    SMSG_SERVER_BUCK_DATA,                       // = 0x41D,
    SMSG_SERVER_BUCK_DATA_START,                 // = 0x4A3,
    SMSG_SERVER_INFO_RESPONSE,                   // = 0x4A1,
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE, // = 0x3A5,
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE,           // = 0x3A4,
    SMSG_SET_FACTION_ATWAR,                      // = 0x313,
    SMSG_SET_FACTION_STANDING,                   // = 0x124,
    SMSG_SET_ITEM_PURCHASE_DATA,                 // = 0x4B2,
    SMSG_SET_PHASE_SHIFT,                        // = 0x47C,
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT,       // = 0x41A,
    SMSG_SET_VEHICLE_REC_ID,                     // = 0x4A7,
    SMSG_SHOWTAXINODES,                          // = 0x1A9,
    SMSG_SHOW_BANK,                              // = 0x1B8,
    SMSG_SHOW_MAILBOX,                           // = 0x297,
    SMSG_SOCKET_GEMS,                            // = 0x50B,
    SMSG_SPELLBREAKLOG,                          // = 0x14F,
    SMSG_SPELLDAMAGESHIELD,                      // = 0x24F,
    SMSG_SPELLDISPELLOG,                         // = 0x27B,
    SMSG_SPELLENERGIZELOG,                       // = 0x151,
    SMSG_SPELLHEALLOG,                           // = 0x150,
    SMSG_SPELLINSTAKILLLOG,                      // = 0x32F,
    SMSG_SPELLLOGMISS,                           // = 0x24B,
    SMSG_SPELLNONMELEEDAMAGELOG,                 // = 0x250,
    SMSG_SPELLORDAMAGE_IMMUNE,                   // = 0x263,
    SMSG_SPELLSTEALLOG,                          // = 0x333,
    SMSG_SPELL_CHANCE_PROC_LOG,                  // = 0x3AA,
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK,           // = 0x404,
    SMSG_SPELL_DELAYED,                          // = 0x1E2,
    SMSG_SPELL_FAILED_OTHER,                     // = 0x2A6,
    SMSG_SPELL_FAILURE,                          // = 0x133,
    SMSG_SPELL_UPDATE_CHAIN_TARGETS,             // = 0x330,
    SMSG_SPIRIT_HEALER_CONFIRM,                  // = 0x222,
    SMSG_SPLINE_MOVE_FEATHER_FALL,               // = 0x305,
    SMSG_SPLINE_MOVE_GRAVITY_DISABLE,            // = 0x4D3,
    SMSG_SPLINE_MOVE_GRAVITY_ENABLE,             // = 0x4D4,
    SMSG_SPLINE_MOVE_LAND_WALK,                  // = 0x30A,
    SMSG_SPLINE_MOVE_NORMAL_FALL,                // = 0x306,
    SMSG_SPLINE_MOVE_ROOT,                       // = 0x31A,
    SMSG_SPLINE_MOVE_SET_FLYING,                 // = 0x422,
    SMSG_SPLINE_MOVE_SET_HOVER,                  // = 0x307,
    SMSG_SPLINE_MOVE_SET_RUN_MODE,               // = 0x30D,
    SMSG_SPLINE_MOVE_SET_WALK_MODE,              // = 0x30E,
    SMSG_SPLINE_MOVE_START_SWIM,                 // = 0x30B,
    SMSG_SPLINE_MOVE_STOP_SWIM,                  // = 0x30C,
    SMSG_SPLINE_MOVE_UNROOT,                     // = 0x304,
    SMSG_SPLINE_MOVE_UNSET_FLYING,               // = 0x423,
    SMSG_SPLINE_MOVE_UNSET_HOVER,                // = 0x308,
    SMSG_SPLINE_MOVE_WATER_WALK,                 // = 0x309,
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED,           // = 0x386,
    SMSG_SPLINE_SET_FLIGHT_SPEED,                // = 0x385,
    SMSG_SPLINE_SET_PITCH_RATE,                  // = 0x45E,
    SMSG_SPLINE_SET_RUN_BACK_SPEED,              // = 0x2FF,
    SMSG_SPLINE_SET_RUN_SPEED,                   // = 0x2FE,
    SMSG_SPLINE_SET_SWIM_BACK_SPEED,             // = 0x302,
    SMSG_SPLINE_SET_SWIM_SPEED,                  // = 0x300,
    SMSG_SPLINE_SET_TURN_RATE,                   // = 0x303,
    SMSG_SPLINE_SET_WALK_SPEED,                  // = 0x301,
    SMSG_STABLE_RESULT,                          // = 0x273,
    SMSG_START_MIRROR_TIMER,                     // = 0x1D9,
    SMSG_STOP_MIRROR_TIMER,                      // = 0x1DB,
    SMSG_SUMMON_CANCEL,                          // = 0x424,
    SMSG_SUMMON_REQUEST,                         // = 0x2AB,
    SMSG_SUPERCEDED_SPELL,                       // = 0x12C,
    SMSG_SUSPEND_COMMS,                          // = 0x50F,
    SMSG_TALENTS_INVOLUNTARILY_RESET,            // = 0x4FA,
    SMSG_TAXINODE_STATUS,                        // = 0x1AB,
    SMSG_TEST_DROP_RATE_RESULT,                  // = 0x295,
    SMSG_THREAT_CLEAR,                           // = 0x485,
    SMSG_THREAT_REMOVE,                          // = 0x484,
    SMSG_THREAT_UPDATE,                          // = 0x483,
    SMSG_TOTEM_CREATED,                          // = 0x413,
    SMSG_TRIGGER_MOVIE,                          // = 0x464,
    SMSG_TURN_IN_PETITION_RESULTS,               // = 0x1C5,
    SMSG_UNKNOWN_1311,                           // = 0x51F, // related to transform
    SMSG_UNKNOWN_1312,                           // = 0x520, // related to transform
    SMSG_UNKNOWN_1314,                           // = 0x522, // sets unit+4336 to value from packet
    SMSG_UNKNOWN_1315,                           // = 0x523, // related to opcode 0x522
    SMSG_UNKNOWN_1316,                           // = 0x524, // sets unit+4338 to value from packet
    SMSG_UNKNOWN_1317,                           // = 0x525, // sets unit+4340 to value from packet
    SMSG_UNKNOWN_1329,                           // = 0x531, // faction related
    SMSG_UPDATE_COMBO_POINTS,                    // = 0x39D,
    SMSG_UPDATE_LAST_INSTANCE,                   // = 0x320,
    SMSG_USERLIST_ADD,                           // = 0x3F0,
    SMSG_USERLIST_REMOVE,                        // = 0x3F1,
    SMSG_USERLIST_UPDATE,                        // = 0x3F2,
    SMSG_USE_EQUIPMENT_SET_RESULT,               // = 0x4D6,
    SMSG_VOICE_CHAT_STATUS,                      // = 0x3E3,
    SMSG_VOICE_PARENTAL_CONTROLS,                // = 0x3B1,
    SMSG_VOICE_SESSION_ADJUST_PRIORITY,          // = 0x3A0,
    SMSG_VOICE_SESSION_ENABLE,                   // = 0x3B0,
    SMSG_VOICE_SESSION_LEAVE,                    // = 0x39F,
    SMSG_VOICE_SESSION_ROSTER_UPDATE,            // = 0x39E,
    SMSG_VOICE_SET_TALKER_MUTED,                 // = 0x3A2,
    SMSG_WEATHER,                                // = 0x2F4,
    SMSG_XPGAIN,                                 // = 0x4ED,
    SMSG_ZONE_MAP,                               // = 0x00B,
    UMSG_DELETE_GUILD_CHARTER,                   // = 0x2C0,
    UMSG_UNKNOWN_1313,                           // = 0x521, // not found
    UMSG_UNKNOWN_1318,                           // = 0x526, // not found
    UMSG_UNKNOWN_1319,                           // = 0x527, // not found
    UMSG_UNKNOWN_1321,                           // = 0x529, // not found
    UMSG_UNKNOWN_1322,                           // = 0x52A, // not found
    UMSG_UNKNOWN_1323,                           // = 0x52B, // not found
    UMSG_UNKNOWN_1324,                           // = 0x52C, // not found
    UMSG_UNKNOWN_1325,                           // = 0x52D, // not found
    UMSG_UNKNOWN_1326,                           // = 0x52E, // not found
    UMSG_UNKNOWN_1327,                           // = 0x52F, // not found
    UMSG_UNKNOWN_1328,                           // = 0x530, // not found
    UMSG_UNKNOWN_1330,                           // = 0x532, // not found
    UMSG_UNKNOWN_1331,                           // = 0x533, // not found
    UMSG_UNKNOWN_1332,                           // = 0x534, // not found
    UMSG_UNKNOWN_1333,                           // = 0x535, // not found
    UMSG_UNKNOWN_1334,                           // = 0x536, // not found
    UMSG_UPDATE_GROUP_INFO,                      // = 0x4FE,
    UMSG_UPDATE_GROUP_MEMBERS,                   // = 0x080,
    UMSG_UPDATE_GUILD,                           // = 0x094,
};


#define NUM_MSG_TYPES 0xFFFF

extern void InitOpcodeTable();

/// Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGEDOUT,                  // _player!= NULL or _player == NULL && m_playerRecentlyLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED,                                       // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE      = 0,                               //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE = 2,                               //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE   = 3                                //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;

struct OpcodeHandler
{
    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    void (WorldSession::*handler)(WorldPacket& recvPacket);
    Opcodes opcodeEnum;
};

extern OpcodeHandler opcodeTable[NUM_MSG_TYPES];
extern uint16 opcodesEnumToNumber[MAX_OPCODE_VALUE];

// Lookup opcode name for human understandable logging
inline const char* LookupOpcodeName(uint16 id)
{
    if (id >= NUM_MSG_TYPES)
        return "Received unknown opcode, it's more than max!";

    return opcodeTable[id].name;
}

inline Opcodes LookupOpcodeEnum(uint16 OpcodeValue)
{
    return opcodeTable[OpcodeValue].opcodeEnum;
}

inline uint16 LookupOpcodeNumber(Opcodes enumValue)
{
    // if opcode is old and not updated
    if (enumValue >= MAX_OPCODE_VALUE)
        return NUM_MSG_TYPES;

    return opcodesEnumToNumber[enumValue];
}

typedef UNORDERED_MAP<std::string, uint16> OpcodeTableContainer;
extern OpcodeTableContainer opcodeTableMap;

class OpcodeTableHandler
{
    public:
        void LoadOpcodesFromDB();

        uint16 GetOpcodeTable(const char* name);
};

#define sOpcodeTableHandler ACE_Singleton<OpcodeTableHandler, ACE_Null_Mutex>::instance()

#endif
